### ISSUE TITLE
libcurl error 61: Error while processing content unencoding: invalid block type

### ISSUE THREAD

**Issue by robertgzr** [saldl/saldl#6]
I tried downloading this quite big archived file: 
https://www.cs.cmu.edu/~./enron/enron_mail_20150507.tgz

`saldl` exits with this:

```
[fatal] libcurl returned fatal error (61: Error while processing content unencoding: invalid block type) while downloading chunk 3.
```

In `curl` and it works fine out of the box.

Eventually I got it working by passing the `--no-compress` flag. I'm just trying to understand what was going on there...

**Comment by MoSal** [comment]
You would get the same error with `curl` if you pass `--compress -r '3145728-4194303'`.

I think the problem is server-side. If we request compression (default in saldl), we get this in the responses:

```
< Content-Type: application/x-tar
< Content-Encoding: gzip
```

And if we don't, we get this:

```
< Content-Type: application/x-tar
< Content-Encoding: x-gzip
```

If I'm not mistaken, responses in the 1st case are wrong if the file itself is gzipped, and compression is not being done by the server itself. I'm assuming that's what's going on here.

Is that analysis correct @bagder?

---

FWIW, I already detect and disable compression if both `Content-Type` and `Content-Encoding` point to gzipped content. But that's not the case here.

**Comment by bagder** [comment]
I would argue that asking for range with content-encoded compression means that the client should get a piece of the compressed version of the resource. As such, curl really shouldn't try to automatically decompress it since the chances it would actually work is really slim and would be more of a fluke than anything else. This could probably be considered a curl bug.

`--compress` both asks for compression and enables automatic decompression. You can ask for compression-only without the decompression by instead using `-H "Accept-Encoding: deflate, gzip"`.

**Comment by MoSal** [comment]
@bagder 
We already have `--no-decompress` which sets `CURLOPT_HTTP_CONTENT_DECODING` to `0l`.
Do you recommend that we set this by default?

**Comment by MoSal** [comment]
The more I think about this. I think requesting compression by default was the wrong decision.

If compression was forced by the server, we have two options:
1- Force single-mode (no partial ranges).
2- Decompress after the download is finished.

**Comment by MoSal** [comment]
I did more investigation.

1- If compression is enabled in the server configuration, both Nginx and Apache add
    `Transfer-Encoding: chunked` to the response, and ranges are not supported.

2- The behavior we are seeing from `www.cs.cmu.edu` is caused by having this in
    their Apache configuration:

```
    # AddEncoding allows you to have certain browsers uncompress
    # information on the fly. Note: Not all browsers support this.
    AddEncoding x-compress .Z
    AddEncoding x-gzip .gz .tgz
```

Unfortunately, they didn't uncomment this part:

```
    # If the AddEncoding directives above are commented-out, then you
    # probably should define those extensions to indicate media types:
    #AddType application/x-compress .Z
    #AddType application/x-gzip .gz .tgz
```

So, IMHO, this is both a server configuration error, and an Apache bug.

@bagder The above information might interest you.

As far as `saldl` is concerned, compression will not be requested by default anymore.
And single-mode will be used if compression was forced in the server response. We will continue
to not decompress if `Content-Type` indicates the original content is in gzip format.
